global:
  namespace: default

postgres_database:
  enabled: true
  name: postgres-database
  username: root
  password: root
  database: postgres-database

flowset_control:
  name: flowset-control
  port: 8081
  default_username: ""
  default_password: ""
