apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.flowset_control.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.flowset_control.port }}
      targetPort: {{ .Values.flowset_control.port }}
