apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
spec:
  tls:
    - hosts:
        - flowset-control.test.terrabyte.lrz.de
      secretName: wildcard-tls
  rules:
    - host: flowset-control.test.terrabyte.lrz.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flowset-control-app-service
                port:
                  number: {{ .Values.flowset_control.port }}
