apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
spec:
  ingressClassName: apisix
  http:
  - name: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
    backends:
    - serviceName: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
      servicePort: 80
    match:
      hosts:
        {{- with .Values.flowset_control.hosts }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      paths:
      - /
