apiVersion: v1
kind: Service
metadata:
  name: flowset-control-app-service
spec:
  selector:
    app: flowset-control-app
  ports:
    - port: {{ .Values.flowset_control.port }}
      targetPort: {{ .Values.flowset_control.port }}
