apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
spec:
  ingressClassName: apisix
  http:
  - name: {{ .Release.Name }}-{{ .Values.flowset_control.name }}
    backends:
    - serviceName: {{ .Release.Name }}-{{ .Values.flowset-control.name }}
      servicePort: 80
    match:
      hosts:
      - flowset-control.test.terrabyte.lrz.de
      paths:
      - /
